name: Build

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

    - name: Create package
      uses: vimtor/action-zip@v1.1
      with:
        files: build/src/Release/psd_writer.lib build/src/Release/psd_writer.dll
        dest: build/psd_writer-${{ github.ref_name }}-windows-x64.zip
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: psd_writer ${{ github.ref_name }}
        artifacts: build/psd_writer-${{ github.ref_name }}-windows-x64.zip
        generateReleaseNotes: true
